### ISSUE TITLE
setfont: ERROR

### ISSUE THREAD

**Issue by PJ-568** [oldherl/syllazh#2]
**Device Information | 设备信息**
 - SOC: [S905L]
 - Model [MiBox 4C]

**Armbian Version | 系统版本**
 - Image Name: [[Armbian_24.8.0_amlogic_s905l_bookworm_6.1.98_server_2024.07.15.img](https://github.com/ophub/amlogic-s9xxx-armbian)]
 - Kernel Version: [6.1.98]
 - Release: [bookworm]

**Describe the bug | 问题描述**

```shell
sudo setfont syllazh

setfont: ERROR psffontop.c:179 read_fontfile: ■■■■
setfont: ERROR setfont.c:58 do_loadfont: ■■■■■■■ 0
```

**Comment by oldherl** [comment]
感谢您的兴趣。
那些黑色方块是什么字符？另外可否确认你的内核版本是否包含了 https://lore.kernel.org/lkml/20221218003339.263695493@ens-lyon.org/t/ 这个patch？

**Comment by oldherl** [comment]
哦，可能不是内核版本，而是kbd版本

**Comment by oldherl** [comment]
经检测，`psffontop.c:179 read_fontfile: ■■■■` 是这个错误 `Font is too big` 的翻译 字体过大：
https://github.com/legionus/kbd/blob/478b7cafa5f8d38108dc5a61f8afcd0891846372/src/libkfont/psffontop.c#L179
也就是旧版本的setfont不支持大于 65535（约64KB，未研究是压缩前还是压缩后）的字体。
而本字体的体积大于上述限制。

在 2.6rc1 之后，上述限制放宽到了 4194304（约4MB）。所以本字体需要 setfont >= 2.6rc1 使用。
