### ISSUE TITLE
wo xie xie ni

### ISSUE THREAD

**Issue by gmicroul** [oldherl/syllazh#4]
![image](https://github.com/user-attachments/assets/c10db7b1-204a-467d-a89a-312c2f022512)
arch arm测试了，效果还不错，毕竟fbterm没编译成功，只有you，wo xie xie ni。

**Comment by gmicroul** [comment]
跟fbterm在alpine arm的体验差不多，还是挡住了keyboard，切换等都有延时。

**Comment by oldherl** [comment]
本项目只提供字体，你所说的问题似乎与此无关。
